# Generated by Django 5.2.8 on 2025-11-22 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('max_speed', models.FloatField()),
                ('train_type', models.CharField(choices=[('passenger', 'Passenger'), ('cargo', 'Cargo'), ('highspeed', 'High-Speed')], max_length=20)),
                ('manufacturer', models.CharField(max_length=100)),
                ('year_built', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_code', models.CharField(max_length=20, unique=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_destination', to='tamper_report.station')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_origin', to='tamper_report.station')),
            ],
        ),
        migrations.CreateModel(
            name='TrainTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_weight', models.FloatField()),
                ('average_speed', models.FloatField()),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tamper_report.route')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tamper_report.train')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_latitude', models.FloatField()),
                ('start_longitude', models.FloatField()),
                ('end_latitude', models.FloatField()),
                ('end_longitude', models.FloatField()),
                ('lift_mm', models.FloatField()),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('date_fixed', models.DateTimeField(blank=True, null=True)),
                ('state', models.IntegerField(choices=[(1, 'Pending'), (2, 'In Process'), (3, 'Fixed'), (4, 'Unsolved')], default=1)),
                ('train_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tamper_report.traintrip')),
            ],
        ),
    ]
