# Generated by Django 5.2.8 on 2025-11-23 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamper_report', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TamperMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('year_built', models.IntegerField()),
                ('weight', models.FloatField()),
                ('max_speed', models.FloatField()),
                ('working_speed', models.FloatField()),
                ('tamper_type', models.CharField(choices=[('unimat', 'Unimat'), ('09-3x', '09-3X'), ('dynamic', 'Dynamic Tamper'), ('plain_line', 'Plain Line Tamper')], max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='report',
            old_name='lift_mm',
            new_name='lift_left_mm',
        ),
        migrations.RemoveField(
            model_name='report',
            name='train_trip',
        ),
        migrations.RemoveField(
            model_name='train',
            name='name',
        ),
        migrations.AddField(
            model_name='report',
            name='lift_right_mm',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('train_trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tamper_report.traintrip')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='report_batch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tamper_report.reportbatch'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TamperOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tamper_report.reportbatch')),
                ('tamper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tamper_report.tampermachine')),
            ],
        ),
    ]
