# Generated by Django 5.2.8 on 2025-11-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamper_report', '0002_tampermachine_rename_lift_mm_report_lift_left_mm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='lift_left_mm',
            new_name='adjustment_left_mm',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='lift_right_mm',
            new_name='adjustment_right_mm',
        ),
        migrations.AddField(
            model_name='report',
            name='lift_mm',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
