# Generated by Django 5.2.8 on 2025-11-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamper_report', '0004_rename_lift_mm_report_lift_left_mm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tampermachine',
            name='tamper_type',
            field=models.CharField(choices=[('unimat_4s', 'Unimat 4S (Universal)'), ('unimat_08_475', 'Unimat 08-475/4S (Desvíos)'), ('09_3x_dyn', '09-3X Dynamic (Alto Rendimiento)'), ('09_32_csm', '09-32 CSM (Línea Continua)'), ('dynamic_9000', 'Dynamic 9000 (Estabilización/Tampeo)'), ('pms_2030', 'PMS 2030 (Plasser Measuring System)'), ('duomatic_09', 'Duomatic 09 (Doble Bateadora)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tamperoperation',
            name='end_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
