# Generated by Django 5.2.8 on 2025-11-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamper_report', '0005_alter_tampermachine_tamper_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamperoperation',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
